# Generated by Django 5.2 on 2025-04-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studetails',
            field=models.CharField(max_length=300),
        ),
    ]
