# Generated by Django 5.2 on 2025-05-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=50, unique=True)),
                ('depdis', models.CharField(max_length=200)),
                ('dephod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=20)),
                ('stuemail', models.EmailField(max_length=254)),
                ('stucontact', models.IntegerField()),
                ('studep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department', to_field='depname')),
            ],
        ),
    ]
