# Generated by Django 5.2 on 2025-05-03 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='app.department', to_field='depname'),
        ),
    ]
