# Generated by Django 5.2.3 on 2025-06-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField(blank=True, unique=True)),
                ('day', models.IntegerField(blank=True)),
                ('person', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('date', models.DateField(blank=True, default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
