# Generated by Django 5.2.3 on 2025-06-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registrations_delete_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='mode',
        ),
    ]
