# Generated by Django 5.2.3 on 2025-06-14 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_registrations_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='contact',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='person',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
