# Generated by Django 5.2.3 on 2025-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registrations_mode_alter_registrations_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='password',
        ),
        migrations.AlterField(
            model_name='registrations',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
