# Generated by Django 5.2 on 2025-04-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adharno', models.IntegerField()),
                ('createdby', models.CharField(max_length=50)),
                ('alloted_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('adharno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.adhaar')),
            ],
        ),
    ]
