# Generated by Django 5.2 on 2025-04-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhaar',
            name='adharno',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='adharno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.adhaar', to_field='adharno'),
        ),
    ]
