# Generated by Django 5.2 on 2025-05-01 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_adhaar_adharno_alter_citizen_adharno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='adharno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='xyz', to='app.adhaar', to_field='adharno'),
        ),
    ]
