# Generated by Django 5.2.1 on 2025-05-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cybrom',
            new_name='mydjangodatabase',
        ),
    ]
