# Generated by Django 5.2.1 on 2025-06-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_phone', models.IntegerField(unique=True)),
                ('user_dob', models.IntegerField()),
                ('user_gender', models.CharField(max_length=50)),
                ('user_profile', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('user_pass', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
