# Generated by Django 5.2 on 2025-04-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_basefield_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basefield',
            options={'ordering': ['name'], 'verbose_name_plural': 'My Custom Model'},
        ),
    ]
