# Generated by Django 5.2 on 2025-04-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stuimage',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
