# Generated by Django 5.2 on 2025-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
