# Generated by Django 5.2.1 on 2025-05-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_contact', models.IntegerField()),
                ('emp_age', models.IntegerField()),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_pass', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
