# Generated by Django 5.2.1 on 2025-05-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
