# Generated by Django 5.2.1 on 2025-05-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee_emp_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=50)),
                ('info_contact', models.IntegerField()),
                ('info_dob', models.DateField()),
                ('info_resume', models.CharField(max_length=200)),
                ('info_image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
