# Generated by Django 5.2.1 on 2025-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_newentry_delete_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='newentry',
            name='admin_opinion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
