# Generated by Django 5.2.1 on 2025-05-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_newentry_admin_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='info_contact',
            field=models.IntegerField(unique=True),
        ),
    ]
