# Generated by Django 5.2.1 on 2025-05-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_discount_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FormattedBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.book',),
        ),
        migrations.CreateModel(
            name='OrderedBook',
            fields=[
            ],
            options={
                'ordering': ['-published_date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.book',),
        ),
        migrations.CreateModel(
            name='RecentBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.book',),
        ),
    ]
